apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
  annotations:
    avp.kubernetes.io/path: "secrets.sops"
spec:
  project: default
  sources:
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: overseerr
              fullnameOverride: overseerr
              ingressClassName: nginx
              annotations:
                external-dns.alpha.kubernetes.io/hostname: <overseerr | jsonPath {.url}>
                cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
              rules:
                - host: <overseerr | jsonPath {.url}>
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: overseerr
                            port: 
                              number: 5055
              tls:
                 - secretName: overseerr-tls
                   hosts:
                     - <overseerr | jsonPath {.url}>
    - chart: overseerr
      repoURL: tccr.io/truecharts
      targetRevision: 15.1.3
      helm:
        version: v3
        valuesObject:
          persistence:
            config:
              enabled: true
              type: hostPath
              mountPath: "/app/config"
              hostPath: /mnt/kube/overseerr/config
              hostPathType: DirectoryOrCreate
          portal:
            open:
              enabled: false
  destination:
    name: "in-cluster"
    namespace: overseerr
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
