apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  annotations:
    avp.kubernetes.io/path: "secrets.sops"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.7.0
    helm:
      version: v3
      valuesObject:
  destination:
    name: "in-cluster"
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
