apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  annotations:
    avp.kubernetes.io/path: "secrets.sops"
spec:
  project: default
  source:
    chart: qbittorrent
    repoURL: tccr.io/truecharts
    targetRevision: 21.1.3
    helm:
      version: v3
      valuesObject:
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: "/config"
            hostPath: /mnt/kube/qbittorrent/config
            hostPathType: DirectoryOrCreate
          downloads:
            enabled: true
            type: hostPath
            mountPath: "/downloads"
            hostPath: /mnt/kube/qbittorrent/downloads
            hostPathType: DirectoryOrCreate
        portal:
          open:
            enabled: false
  destination:
    name: "in-cluster"
    namespace: qbittorrent
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
