apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  annotations:
    avp.kubernetes.io/path: "secrets.sops"
spec:
  project: default
  source:
    chart: transmission
    repoURL: tccr.io/truecharts
    targetRevision: 22.1.3
    helm:
      version: v3
      valuesObject:
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: "/config"
            hostPath: /mnt/kube/transmission/config
            hostPathType: DirectoryOrCreate
          downloads:
            enabled: true
            type: hostPath
            mountPath: "/downloads"
            hostPath: /mnt/kube/transmission/downloads
            hostPathType: DirectoryOrCreate
  destination:
    name: "in-cluster"
    namespace: transmission
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
