apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: adguard-home
      repoURL: tccr.io/truecharts
      targetRevision: 11.1.7
      helm:
        version: v3
        valuesObject:
          podOptions:
            nodeSelector:
              zone: home
              nuc: "2"
          service:
            dns-tcp:
              annotations:
                tailscale.com/expose: "true"
              externalIPs:
                - 192.168.1.101
            dns-udp:
              annotations:
                tailscale.com/expose: "true"
              externalIPs:
                - 192.168.1.101
            dns-https:
              enabled: false
            dns-https-udp:
              enabled: false
            dns-crypt:
              enabled: false
            dns-crypt-udp:
              enabled: false
            dns-quic-udp-1:
              enabled: false
          persistence:
            config:
              enabled: true
              type: pvc
              storageClass: nfs-client
              size: 50Mi
              mountPath: /opt/adguardhome/conf
            data:
              enabled: true
              type: pvc
              storageClass: nfs-client
              size: 200Mi
              mountPath: /opt/adguardhome/work
          ingress:
            main:
              integrations:
                homepage:
                  widget:
                    type:
          portal:
            open:
              enabled: false
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: adguard-home
              fullnameOverride: adguard-home
              ingressClassName: tailscale
              defaultBackend:
                service:
                  name: adguard-home
                  port:
                    number: 10232
              tls:
                 - hosts:
                     - adguard-home
  destination:
    name: "in-cluster"
    namespace: adguard-home
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
