apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: crowdsec
    repoURL:  https://crowdsecurity.github.io/helm-charts
    targetRevision: 0.13.0
    helm:
      version: v3
      valuesObject:
        container_runtime: containerd
        agent:
          acquisition:
            - namespace: ingress-nginx
              podName: ingress-nginx-controller-*
              program: nginx
          env:
          - name: COLLECTIONS
            value: "crowdsecurity/nginx"
          - name: PARSERS
            value: "crowdsecurity/cri-logs"
          - name: DISABLE_PARSERS
            value: "crowdsecurity/whitelists"
        lapi:
          dashboard:
            enabled: true
  destination:
    name: "in-cluster"
    namespace: crowdsec
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
