apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: crowdsec
      repoURL:  https://crowdsecurity.github.io/helm-charts
      targetRevision: 0.18.1
      helm:
        version: v3
        valuesObject:
          container_runtime: containerd
          agent:
            acquisition:
              - namespace: ingress-nginx
                podName: ingress-nginx-controller-*
                program: nginx
            env:
            - name: COLLECTIONS
              value: "crowdsecurity/nginx"
            - name: PARSERS
              value: "crowdsecurity/cri-logs"
            - name: DISABLE_PARSERS
              value: "crowdsecurity/whitelists"
            extraVolumes:
            - name: custom-http-context
              configMap:
                name: custom-http-context
            extraVolumeMounts:
            - name: custom-http-context
              mountPath: /etc/crowdsec/contexts/custom_http_context.yaml
              subPath: custom_http_context.yaml
          lapi:
            dashboard:
              enabled: true
            env:
            - name: BOUNCER_KEY_ingress-nginx
              value: <crowdsec | jsonPath {.nginx-bouncer}>
    - chart: k8s-resources
      repoURL: ghcr.io/deliveryhero/helm-charts
      targetRevision: 0.8.1
      helm:
        version: v3
        valuesObject:
          ConfigMaps:
          - name: custom-http-context
            fullnameOverride: custom-http-context
            multiline_data:
              custom_http_context.yaml: |
                context:
                 http_referer:
                  - evt.Parsed.http_referer
                 target_fqdn:
                  - evt.Parsed.target_fqdn
  destination:
    name: "in-cluster"
    namespace: crowdsec
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
