apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: flaresolverr
      repoURL: tccr.io/truecharts
      targetRevision: 15.5.4
      helm:
        version: v3
        valuesObject:
          image:
            tag: pr-1282
          persistence:
            config:
              enabled: false
          portal:
            open:
              enabled: false
  destination:
    name: "in-cluster"
    namespace: flaresolverr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
