apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: influxdb
    repoURL: https://helm.influxdata.com
    targetRevision: 4.12.5
    helm:
      version: v3
      valuesObject:
        persistence:
          size: 10Gi
        service:
          annotations:
            tailscale.com/expose: "true"
        setDefaultUser:
          enabled: true
          password: <influxdb | jsonPath {.password}>
        config:
          graphite:
           enabled: true
           database: "graphitedb"
           retention-policy: ""
           bind-address: ":2003"
           protocol: "tcp"
           consistency-level: "one"
           templates:
             - "servers.* .host.resource.measurement.field*"
  destination:
    name: "in-cluster"
    namespace: influxdb
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: influxdb2
    repoURL: https://helm.influxdata.com
    targetRevision: 2.1.2
    helm:
      version: v3
      valuesObject:
        persistence:
          size: 10Gi
        service:
          annotations:
            tailscale.com/expose: "true"
        adminUser:
          password: <influxdb | jsonPath {.password}>
          token: <influxdb | jsonPath {.token}>
  destination:
    name: "in-cluster"
    namespace: influxdb2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: telegraf
    repoURL: https://helm.influxdata.com
    targetRevision: 1.8.55
    helm:
      version: v3
      valuesObject:
        service:
          annotations:
            tailscale.com/expose: "true"
        config:
          outputs:
            - influxdb_v2:
                urls:
                  - http://influxdb2.influxdb2.svc.cluster.local
                bucket: default
                organization: influxdata
                token: <influxdb | jsonPath {.token}>
            - file:
                files:
                  - stdout
                flush_interval: 1s
                flush_jitter: 1s
                metric_batch_size: 10
          inputs:
            - socket_listener:
                service_address: tcp://:12003
                data_format: graphite
                templates:
                  - os.host.measurement.type.field
  destination:
    name: "in-cluster"
    namespace: telegraf
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
