apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
spec:
  project: default
  source:
    chart: local-path-provisioner
    repoURL: https://tieum.github.io/local-path-provisioner/
    targetRevision: v0.0.28
    helm:
      version: v3
      valuesObject:
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /mnt/kube/local-path-provisioner
  destination:
    name: "in-cluster"
    namespace: local-path-provisioner
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
