apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      version: v3
      valuesObject:
        nfs:
          server: <nfs | jsonPath {.server}>
          path: <nfs | jsonPath {.path}>
  destination:
    name: "in-cluster"
    namespace: nfs-provisioner
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
