apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: organizr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: organizr
      repoURL: tccr.io/truecharts
      targetRevision: 20.3.2
      helm:
        version: v3
        valuesObject:
          image:
            repository: ghcr.io/organizr/organizr
            tag: latest
          persistence:
            config:
              size: 600Mi
            data:
              size: 200Mi
          workload:
            main:
              podSpec:
                containers:
                  main:
                    env:
                      branch: v2-develop
    - chart: k8s-resources
      repoURL: ghcr.io/deliveryhero/helm-charts
      targetRevision: 0.8.0
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: organizr
              fullnameOverride: organizr
              ingressClassName: tailscale
              rules:
                - http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: organizr
                            port:
                              number: 10022
              tls:
                 - hosts:
                     - dash
  destination:
    name: "in-cluster"
    namespace: organizr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
