apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: pihole
      repoURL: tccr.io/truecharts
      targetRevision: 18.4.0
      helm:
        version: v3
        valuesObject:
          podOptions:
            nodeSelector:
              zone: home
              nuc: "1"
          securityContext:
            container:
              capabilities:
                add:
                  - NET_ADMIN
                  - SETFCAP
                  - SETPCAP
                  - KILL
                  - NET_RAW
          service:
            dns:
              annotations:
                tailscale.com/expose: "true"
              externalIPs:
                - 192.168.1.100
          persistence:
            config:
              enabled: true
              type: hostPath
              mountPath: "/etc/pihole"
              hostPath: /mnt/kube/pihole/config
              hostPathType: DirectoryOrCreate
            dnsmasq:
              enabled: true
              type: hostPath
              mountPath: "/etc/dnsmasq.d"
              hostPath: /mnt/kube/pihole/dnsmasq.d
              hostPathType: DirectoryOrCreate
          portal:
            open:
              enabled: false
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: pihole
              fullnameOverride: pihole
              ingressClassName: tailscale
              defaultBackend:
                service:
                  name: pihole
                  port:
                    number: 9089
              tls:
                 - hosts:
                     - pihole
  destination:
    name: "in-cluster"
    namespace: pihole
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
