apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: plex-media-server
      repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      targetRevision: 0.4.0
      helm:
        version: v3
        valuesObject:
          image:
            repository: plexinc/pms-docker
            tag: 1.41.0.8994-f2c27da23
          ingress:
            enabled: true
            url: <plex| jsonPath {.url}>
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/hostname: <plex | jsonPath {.url}>
              cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
          pms:
            configExistingClaim: pvc-plex
          service:
            type: NodePort
          extraEnv:
            PLEX_CLAIM: <plex | jsonPath {.claim}>
            PLEX_UID: 568
            PLEX_GID: 568
          extraVolumes:
            - name: movies
              nfs:
                server: <nfs | jsonPath {.ip}>
                path: <nfs | jsonPath {.mountpoint}>/movies
            - name: tv
              nfs:
                server: <nfs | jsonPath {.ip}>
                path: <nfs | jsonPath {.mountpoint}>/tv
            - name: music
              nfs:
                server: <nfs | jsonPath {.ip}>
                path: <nfs | jsonPath {.mountpoint}>/music
          extraVolumeMounts:
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv
            - name: music
              mountPath: /music
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          CustomResources:
            - name: pv-plex
              fullnameOverride: pv-plex
              apiVersion: v1
              kind: PersistentVolume
              spec:
               storageClassName: manual
               capacity:
                 storage: 2Gi
               accessModes:
                 - ReadWriteOnce
               hostPath:
                 path: "/mnt/kube/plex"
            - name: pvc-plex
              fullnameOverride: pvc-plex
              apiVersion: v1
              kind: PersistentVolumeClaim
              spec:
               storageClassName: manual
               accessModes:
                 - ReadWriteOnce
               resources:
                  requests:
                    storage: 2Gi
  destination:
    name: "in-cluster"
    namespace: plex
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
