apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plextraktsync
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: plextraktsync
      repoURL: tccr.io/truecharts
      targetRevision: 9.8.1
      helm:
        version: v3
        valuesObject:
          plextraktsync:
            cron_enabled: false
          persistence:
            config:
              size: 50Mi
          portal:
            open:
              enabled: false
  destination:
    name: "in-cluster"
    namespace: plextraktsync
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
