apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 62.2.1
    helm:
      version: v3
      valuesObject:
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/hostname: <prometheus| jsonPath {.url}>
              cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
              nginx.ingress.kubernetes.io/auth-url: "https://<eas | jsonPath {.endpoint}>/verify?redirect_http_code=401&config_token_store_id=primary&config_token_id=github"
              nginx.ingress.kubernetes.io/auth-signin: "https://<eas | jsonPath {.endpoint}>/nginx/auth-signin?rd=$auth_redirect"
              nginx.ingress.kubernetes.io/configuration-snippet: |
                auth_request_set $auth_redirect $upstream_http_location;
            hosts:
              - <prometheus| jsonPath {.url}>
            tls:
              - secretName: prometheus-general-tls
                hosts:
                - <prometheus| jsonPath {.url}>
        grafana:
          adminPassword: <grafana | jsonPath {.adminpassword}>
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/hostname: <grafana | jsonPath {.url}>
              cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
              nginx.ingress.kubernetes.io/auth-url: "https://<eas | jsonPath {.endpoint}>/verify?redirect_http_code=401&config_token_store_id=primary&config_token_id=github"
              nginx.ingress.kubernetes.io/auth-signin: "https://<eas | jsonPath {.endpoint}>/nginx/auth-signin?rd=$auth_redirect"
              nginx.ingress.kubernetes.io/configuration-snippet: |
                auth_request_set $auth_redirect $upstream_http_location;
            hosts:
              - <grafana | jsonPath {.url}>
            tls:
              - secretName: grafana-general-tls
                hosts:
                - <grafana | jsonPath {.url}>
  destination:
    name: "in-cluster"
    namespace: prometheus
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
