apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: prowlarr
      repoURL: tccr.io/truecharts
      targetRevision: 18.7.1
      helm:
        version: v3
        valuesObject:
          persistence:
            config:
              enabled: true
              type: pvc
              storageClass: nfs-client
              size: 400Mi
              mountPath: "/config"
          portal:
            open:
              enabled: false
          updated: false
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: prowlarr
              fullnameOverride: prowlarr
              ingressClassName: nginx
              annotations:
                external-dns.alpha.kubernetes.io/hostname: <prowlarr | jsonPath {.url}>
                cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
                nginx.ingress.kubernetes.io/auth-url: "https://<eas | jsonPath {.endpoint}>/verify?redirect_http_code=401&config_token_store_id=primary&config_token_id=github"
                nginx.ingress.kubernetes.io/auth-signin: "https://<eas | jsonPath {.endpoint}>/nginx/auth-signin?rd=$auth_redirect"
                nginx.ingress.kubernetes.io/configuration-snippet: |
                  auth_request_set $auth_redirect $upstream_http_location;
              rules:
                - host: <prowlarr | jsonPath {.url}>
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: prowlarr
                            port:
                              number: 9696
              tls:
                 - secretName: prowlarr-tls
                   hosts:
                     - <prowlarr | jsonPath {.url}>
  destination:
    name: "in-cluster"
    namespace: prowlarr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
