apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: qbittorrent
      repoURL: tccr.io/truecharts
      targetRevision: 21.1.11
      helm:
        version: v3
        valuesObject:
          addons:
            vpn:
              type: gluetun
              killSwitch: true
              envList:
                - name: VPN_SERVICE_PROVIDER
                  value: protonvpn
                - name: VPN_PORT_FORWARDING_PROVIDER
                  value: protonvpn
                - name: PORT_FORWARD_ONLY
                  value: on
                - name: VPN_TYPE
                  value: wireguard
                - name: WIREGUARD_PRIVATE_KEY
                  value: <qbittorrent | jsonPath {.vpn.priv}> 
          qbitportforward:
            enabled: true
            QBT_USERNAME: <qbittorrent | jsonPath {.user}>"
            QBT_PASSWORD: <qbittorrent | jsonPath {.password}>"
          podOptions:
            nodeSelector:
              zone: "cloud"
          service:
            torrent:
              enabled: true
              type: NodePort
              ports:
                torrent:
                  enabled: true
                  port: 6881
                  targetPort: 6881
                  protocol: tcp
                  nodePort: 31299
                torrentudp:
                  enabled: true
                  port: 6881
                  targetPort: 6881
                  protocol: udp
                  nodePort: 30609
          persistence:
            config:
              enabled: true
              type: pvc
              storageClass: nfs-client 
              size: 50Mi
              mountPath: "/config"
            downloads:
              enabled: true
              type: nfs 
              server: <nfs | jsonPath {.server}>
              path: <nfs | jsonPath {.path}>/qbittorrent-downloads
              mountPath: "/downloads"
              accessModes: [ReadWriteMany]
          portal:
            open:
              enabled: false
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: qbittorrent
              fullnameOverride: qbittorrent
              ingressClassName: nginx
              annotations:
                external-dns.alpha.kubernetes.io/hostname: <qbittorrent | jsonPath {.url}>
                cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
                nginx.ingress.kubernetes.io/auth-url: "https://<eas | jsonPath {.endpoint}>/verify?redirect_http_code=401&config_token_store_id=primary&config_token_id=htpasswd"
              rules:
                - host: <qbittorrent | jsonPath {.url}>
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: qbittorrent
                            port:
                              number: 10095
              tls:
                 - secretName: qbittorrent-tls
                   hosts:
                     - <qbittorrent | jsonPath {.url}>
  destination:
    name: "in-cluster"
    namespace: qbittorrent
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
