apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: qbittorrent
      repoURL: tccr.io/truecharts
      targetRevision: 22.4.5
      helm:
        version: v3
        valuesObject:
          addons:
            vpn:
              type: gluetun
              killSwitch: true
              excludedNetworks_IPv4:
                - 10.10.0.0/16
                - 10.96.0.0/12
              inputPorts:
                - 8000
              envList:
                - name: VPN_SERVICE_PROVIDER
                  value: protonvpn
                - name: OPENVPN_USER
                  value: <vpn| jsonPath {.userpmp}>
                - name: OPENVPN_PASSWORD
                  value: <vpn| jsonPath {.password}>
                - name:  VPN_PORT_FORWARDING
                  value: on
                - name: SERVER_COUNTRIES
                  value: France
          qbitportforward:
            enabled: true
            QBT_USERNAME: <qbittorrent | jsonPath {.user}>
            QBT_PASSWORD: <qbittorrent | jsonPath {.password}>
          podOptions:
            nodeSelector:
              zone: "cloud"
          service:
            torrent:
              enabled: true
              type: ClusterIP
              ports:
                torrent:
                  enabled: true
                  port: 6881
                  targetPort: 6881
                  protocol: tcp
                torrentudp:
                  enabled: true
                  port: 6881
                  targetPort: 6881
                  protocol: udp
          persistence:
            config:
              size: 50Mi
            servarr:
              enabled: true
              type: nfs
              server: <nfs | jsonPath {.ip}>
              path: <nfs | jsonPath {.mountpoint}>
              mountPath: "/servarr"
              accessModes: [ReadWriteMany]
          portal:
            open:
              enabled: false
    - chart: k8s-resources
      repoURL: ghcr.io/deliveryhero/helm-charts
      targetRevision: 0.8.1
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: qbittorrent
              fullnameOverride: qbittorrent
              ingressClassName: tailscale
              rules:
                - http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: qbittorrent
                            port:
                              number: 10095
              tls:
                 - hosts:
                     - qbittorrent
  destination:
    name: "in-cluster"
    namespace: qbittorrent
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
