apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
spec:
  project: default
  sources:
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: radarr
              fullnameOverride: radarr
              ingressClassName: nginx
              annotations:
                external-dns.alpha.kubernetes.io/hostname: <radarr | jsonPath {.url}>
                cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
                nginx.ingress.kubernetes.io/auth-url: "https://<eas | jsonPath {.endpoint}>/verify?redirect_http_code=401&config_token_store_id=primary&config_token_id=github"
                nginx.ingress.kubernetes.io/auth-signin: "https://<eas | jsonPath {.endpoint}>/nginx/auth-signin?rd=$auth_redirect"
                nginx.ingress.kubernetes.io/configuration-snippet: |
                  auth_request_set $auth_redirect $upstream_http_location;
              rules:
                - host: <radarr | jsonPath {.url}>
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: radarr
                            port: 
                              number: 7878
              tls:
                 - secretName: radarr-tls
                   hosts:
                     - <radarr | jsonPath {.url}>
    - chart: radarr
      repoURL: tccr.io/truecharts
      targetRevision: 23.4.6
      helm:
        version: v3
        valuesObject:
          persistence:
            config:
              enabled: true
              type: hostPath
              mountPath: "/config"
              hostPath: /mnt/kube/radarr/config
              hostPathType: DirectoryOrCreate
            rootfolder:
              enabled: true
              type: hostPath
              mountPath: "/pcloud"
              hostPath: /mnt/pcloud
              hostPathType: Directory
            downloadscomplete:
              enabled: true
              type: hostPath
              mountPath: "/downloads/complete"
              hostPath: /mnt/kube/qbittorrent/downloads/complete
              hostPathType: Directory
          portal:
            open:
              enabled: false
          updated: false
  destination:
    name: "in-cluster"
    namespace: radarr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
