apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: radarr
      repoURL: tccr.io/truecharts
      targetRevision: 23.24.0
      helm:
        version: v3
        valuesObject:
          credentials:
            minio:
              type: s3
              url: <minio | jsonPath {.endpoint}>
              bucket: "backups"
              accessKey: <minio | jsonPath {.accessKey}>
              secretKey: <minio | jsonPath {.secretKey}>
              encrKey: <minio | jsonPath {.encryptionKey}>
          cnpg:
            main:
              enabled: true
              mode: recovery
              backups:
                enabled: true
                credentials: minio
              recovery:
                method: object_store
                credentials: minio
              user: radarr
              database: radarr
              cluster:
                  storage:
                    size: 1Gi
                    storageClass: longhorn
                  walStorage:
                    size: 2Gi
                    storageClass: longhorn
          workload:
            main:
              podSpec:
                containers:
                  main:
                    env:
                      RADARR__APP__INSTANCENAME: Radarr
                      RADARR__APP__LAUNCHBROWSER: True
                      RADARR__APP__THEME: dark
                      RADARR__AUTH__APIKEY: <radarr | jsonPath {.apiKey}>
                      RADARR__AUTH__METHOD: Forms
                      RADARR__AUTH__REQUIRED: Enabled
                      RADARR__LOG__ANALYTICS_ENABLED: False
                      RADARR__LOG__DBENABLED: False
                      RADARR__LOG__LEVEL: info
                      RADARR__POSTGRES__HOST: radarr-cnpg-main-rw
                      RADARR__POSTGRES__MAINDB: radarr
                      RADARR__POSTGRES__PASSWORD: <radarr | jsonPath {.dbPassword}>
                      RADARR__POSTGRES__PORT: 5432
                      RADARR__POSTGRES__USER: postgres
                      RADARR__SERVER__BINDADDRESS: "*"
                      RADARR__SERVER__ENABLESSL: False
                      RADARR__UPDATE__MECHANISM: Docker
                      RADARR__SERVER__PORT: 7878
                      RADARR__SERVER__SSLCERTPATH: ""
                      RADARR__SERVER__SSLCERTPASSWORD: ""
                      RADARR__SERVER__SSLPORT: 9898
                      RADARR__SERVER__URLBASE: ""
                  exportarr:
                    env:
                      APIKEY: <radarr | jsonPath {.apiKey}>
                      CONFIG: ""
          persistence:
            config:
              size: 1Gi
            servarr:
              enabled: true
              type: nfs
              server: <nfs | jsonPath {.ip}>
              path: <nfs | jsonPath {.mountpoint}>
              mountPath: "/servarr"
              accessModes: [ReadWriteMany]
          portal:
            open:
              enabled: false
          updated: false
    - chart: k8s-resources
      repoURL: ghcr.io/deliveryhero/helm-charts
      targetRevision: 0.8.1
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: radarr
              fullnameOverride: radarr
              ingressClassName: tailscale
              rules:
                - http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: radarr
                            port:
                              number: 7878
              tls:
                 - hosts:
                     - radarr
  destination:
    name: "in-cluster"
    namespace: radarr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
