apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: signal-cli-rest-api
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valuesObject:
        persistence:
          storageClass: longhorn
          storageSize: 50Mi
    path: charts/signal-cli-rest-api
    repoURL: https://github.com/tieum/helm-charts.git
    targetRevision: main
  destination:
    namespace: signal-cli-rest-api
    name: "in-cluster"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
