apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slskd
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: slskd
      repoURL: tccr.io/truecharts
      targetRevision: 3.0.3
      helm:
        version: v3
        valuesObject:
          addons:
            vpn:
              type: gluetun
              killSwitch: true
              excludedNetworks_IPv4:
                - 10.10.0.0/16
                - 10.96.0.0/12
              envList:
                - name: VPN_SERVICE_PROVIDER
                  value: protonvpn
                - name: OPENVPN_USER
                  value: <vpn| jsonPath {.userpmp}>
                - name: OPENVPN_PASSWORD
                  value: <vpn| jsonPath {.password}>
                - name:  VPN_PORT_FORWARDING
                  value: on
                - name: SERVER_COUNTRIES
                  value: France
          workload:
            main:
              podSpec:
                containers:
                  main:
                    env:
                      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
                      SLSKD_SLSK_LISTEN_IP_ADDRESS: 0.0.0.0
                      SLSKD_SLSK_LISTEN_PORT: 50300
                      SLSKD_HTTP_PORT: 5030
                      SLSKD_REMOTE_CONFIGURATION: true
                      APP_DIR: "{{.Values.persistence.data.mountPath }}"
                      SLSKD_SHARED_DIR: "{{ .Values.persistence.nfs.mountPath }}/<slskd | jsonPath {.shareddir}>"
                      SLSKD_DOWNLOADS_DIR: "{{ .Values.persistence.nfs.mountPath }}/<slskd | jsonPath {.downloadscompletedir}>"
                      SLSKD_INCOMPLETE_DIR: "{{ .Values.persistence.nfs.mountPath }}/<slskd | jsonPath {.downloadsincompletedir}>"
                      SLSKD_USERNAME: "<slskd | jsonPath {.username}>"
                      SLSKD_PASSWORD: "<slskd | jsonPath {.password}>"
                      SLSKD_SLSK_USERNAME: "<slskd | jsonPath {.username}>"
                      SLSKD_SLSK_PASSWORD: "<slskd | jsonPath {.password}>"
                      SLSKD_JWT_KEY:
                        secretKeyRef:
                          name: slskd-secrets
                          key: SLSKD_JWT_KEY
          securityContext:
            pod:
              fsGroup: 568
              fsGroupChangePolicy: Always
          persistence:
            data:
              size: 100Mi
            share:
              enabled: false
            nfs:
              enabled: true
              type: nfs
              server: <nfs | jsonPath {.ip}>
              path: <nfs | jsonPath {.mountpoint}>
              mountPath: <slskd | jsonPath {.nfsmountpath}>
              accessModes: [ReadWriteMany]
            incomplete:
              enabled: false
            complete:
              enabled: false
          portal:
            open:
              enabled: false
    - chart: k8s-resources
      repoURL: ghcr.io/deliveryhero/helm-charts
      targetRevision: 0.8.1
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: slskd
              fullnameOverride: slskd
              ingressClassName: tailscale
              rules:
                - http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: slskd
                            port:
                              number: 5030
              tls:
                 - hosts:
                     - slskd
          # chart doesnt handle roles/rolebinding (even with CustomResources), this will have to do for now
          ClusterRoles:
            - name: portfwd
              fullnameOverride: portfwd
              rules:
              - apiGroups: [""]
                resources: [pods]
                verbs: [list]
              - apiGroups: [""]
                resources: [pods/exec]
                verbs: [create, get]
          ClusterRoleBindings:
            - name: portfwd
              fullnameOverride: portfwd
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: portfwd
              subjects:
              - kind: ServiceAccount
                name: default
                namespace: slskd
          CronJobs:
            - name: update-portforward
              fullnameOverride: update-portforward
              schedule: 1-59/5 * * * * #headache incoming if starting value with *
              containers:
                - name: update-portforward
                  image: ghcr.io/tieum/slskd-port-forward-gluetun-server:main
  destination:
    name: "in-cluster"
    namespace: slskd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
