apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: sonarr
      repoURL: tccr.io/truecharts
      targetRevision: 23.8.2
      helm:
        version: v3
        valuesObject:
          credentials:
            minio:
              type: s3
              url: <minio | jsonPath {.endpoint}>
              bucket: "backups"
              accessKey: <minio | jsonPath {.accessKey}>
              secretKey: <minio | jsonPath {.secretKey}>
              encrKey: <minio | jsonPath {.encryptionKey}>
          cnpg:
            main:
              enabled: true
              mode: recovery
              backups:
                enabled: true
                credentials: minio
              recovery:
                method: object_store
                credentials: minio
              user: sonarr
              database: sonarr
              cluster:
                  storage:
                    size: 1Gi
                    storageClass: longhorn
                  walStorage:
                    size: 2Gi
                    storageClass: longhorn
          workload:
            main:
              podSpec:
                containers:
                  main:
                    env:
                      SONARR__APP__INSTANCENAME: Sonarr
                      SONARR__APP__LAUNCHBROWSER: True
                      SONARR__APP__THEME: dark
                      SONARR__AUTH__APIKEY: <sonarr | jsonPath {.apiKey}>
                      SONARR__AUTH__METHOD: Forms
                      SONARR__AUTH__REQUIRED: Enabled
                      SONARR__LOG__ANALYTICS_ENABLED: False
                      SONARR__LOG__DBENABLED: False
                      SONARR__LOG__LEVEL: info
                      SONARR__POSTGRES__HOST: sonarr-cnpg-main-rw
                      SONARR__POSTGRES__MAINDB: sonarr
                      SONARR__POSTGRES__PASSWORD: <sonarr | jsonPath {.dbPassword}>
                      SONARR__POSTGRES__PORT: 5432
                      SONARR__POSTGRES__USER: postgres
                      SONARR__SERVER__BINDADDRESS: "*"
                      SONARR__SERVER__ENABLESSL: False
                      SONARR__UPDATE__MECHANISM: Docker
                      SONARR__SERVER__PORT: 8989
                      SONARR__SERVER__SSLCERTPATH: ""
                      SONARR__SERVER__SSLCERTPASSWORD: ""
                      SONARR__SERVER__SSLPORT: 9898
                      SONARR__SERVER__URLBASE: ""
                  exportarr:
                    env:
                      APIKEY: <sonarr | jsonPath {.apiKey}>
                      CONFIG: ""
                      ENABLE_ADDITIONAL_METRICS: true
          persistence:
            config:
              size: 1Gi
            servarr:
              enabled: true
              type: nfs
              server: <nfs | jsonPath {.ip}>
              path: <nfs | jsonPath {.mountpoint}>
              mountPath: "/servarr"
              accessModes: [ReadWriteMany]
          portal:
            open:
              enabled: false
          updated: false
    - chart: k8s-resources
      repoURL: ghcr.io/deliveryhero/helm-charts
      targetRevision: 0.8.1
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: sonarr
              fullnameOverride: sonarr
              ingressClassName: tailscale
              rules:
                - http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: sonarr
                            port:
                              number: 8989
              tls:
                 - hosts:
                     - sonarr
  destination:
    name: "in-cluster"
    namespace: sonarr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
