apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  annotations:
    avp.kubernetes.io/path: "../secrets.sops.yaml"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: sonarr
      repoURL: tccr.io/truecharts
      targetRevision: 23.2.2
      helm:
        version: v3
        valuesObject:
          cnpg:
            main:
              enabled: true
              user: sonarr
              database: sonarr
              cluster:
                  storage:
                    size: 1Gi
                    storageClass: longhorn
                  walStorage:
                    size: 1Gi
                    storageClass: longhorn
          workload:
            main:
              podSpec:
                containers:
                  main:
                    env:
                      SONARR__APP__INSTANCENAME: Sonarr
                      SONARR__APP__LAUNCHBROWSER: True
                      SONARR__APP__THEME: dark
                      SONARR__AUTH__APIKEY: <sonarr | jsonPath {.apiKey}>
                      SONARR__AUTH__METHOD: Forms
                      SONARR__AUTH__REQUIRED: Enabled
                      SONARR__LOG__ANALYTICS_ENABLED: False
                      SONARR__LOG__DBENABLED: False
                      SONARR__LOG__LEVEL: info
                      SONARR__POSTGRES__HOST: sonarr-cnpg-main-rw
                      SONARR__POSTGRES__MAINDB: sonarr
                      SONARR__POSTGRES__PASSWORD: <sonarr | jsonPath {.dbPassword}>
                      SONARR__POSTGRES__PORT: 5432
                      SONARR__POSTGRES__USER: postgres
                      SONARR__SERVER__BINDADDRESS: "*"
                      SONARR__SERVER__ENABLESSL: False
                      SONARR__UPDATE__MECHANISM: Docker
                      SONARR__SERVER__PORT: 8989
                      SONARR__SERVER__SSLCERTPATH: ""
                      SONARR__SERVER__SSLCERTPASSWORD: ""
                      SONARR__SERVER__SSLPORT: 9898
                      SONARR__SERVER__URLBASE: ""
                  exportarr:
                    env:
                      APIKEY: <sonarr | jsonPath {.apiKey}>
                      CONFIG: ""
          persistence:
            config:
              enabled: true
              type: pvc
              storageClass: nfs-client
              size: 1Gi
              mountPath: "/config"
            servarr:
              enabled: true
              type: nfs
              server: <nfs | jsonPath {.ip}>
              path: <nfs | jsonPath {.mountpoint}>
              mountPath: "/servarr"
              accessModes: [ReadWriteMany]
          portal:
            open:
              enabled: false
          updated: false
    - chart: k8s-resources
      repoURL: https://charts.deliveryhero.io/
      targetRevision: 0.6.6
      helm:
        version: v3
        valuesObject:
          Ingresses:
            - name: sonarr
              fullnameOverride: sonarr
              ingressClassName: nginx
              annotations:
                external-dns.alpha.kubernetes.io/hostname: <sonarr | jsonPath {.url}>
                cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
                nginx.ingress.kubernetes.io/auth-url: "https://<eas | jsonPath {.endpoint}>/verify?redirect_http_code=401&config_token_store_id=primary&config_token_id=github"
                nginx.ingress.kubernetes.io/auth-signin: "https://<eas | jsonPath {.endpoint}>/nginx/auth-signin?rd=$auth_redirect"
                nginx.ingress.kubernetes.io/configuration-snippet: |
                  auth_request_set $auth_redirect $upstream_http_location;
              rules:
                - host: <sonarr | jsonPath {.url}>
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: sonarr
                            port:
                              number: 8989
              tls:
                 - secretName: sonarr-tls
                   hosts:
                     - <sonarr | jsonPath {.url}>
  destination:
    name: "in-cluster"
    namespace: sonarr
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
